INSERT INTO burgers (burger_name, devoured) VALUES ("Pizza Burger", false)
INSERT INTO burgers (burger_name, devoured) VALUES ("Cheese Burger", false)
INSERT INTO burgers (burger_name, devoured) VALUES ("Ham Burger", false)
INSERT INTO burgers (burger_name, devoured) VALUES ("Plain Burger", false)
INSERT INTO burgers (burger_name, devoured) VALUES ("Bacon Burger", false)